### PR TITLE
modify and delete some file

### PR DESCRIPTION
**Pull request by time-river**
merge history

### CODE REVIEW

**Comment by camper42** [comment]
清理一下commit吧

**Comment by seansay** [comment]
👏

**Comment by CDLuminate** [comment]
@time-river the `sda` files is our hard disk SMART log recorded in 2015. At that time I sniffed and predicted the disk failure and I performed backup, finnaly the disk failed some day, but we are safe -- we are immune to severe data loss. Please keep the SMART data, and you can learn something from the plot of some smart data.

I'm object to this merge until the sda data is properly kept instead of simply removal.

**Comment by CDLuminate** [comment]
@time-river maybe our server document `XDLS` is where `sda` data should go. Please check if you have pull  and push permission correctly.

**Comment by camper42** [comment]
目前看来这个repo的作用类似于编年史，服务器相关的“事件”应该写进去
但具体到log之类的，单独的分支或者扔到服务器维护相关那边似乎更合适

另外，个人建议以后可以考虑将成员部分拆到单独的文件

**Pull request closed without merging**
